# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0004_auto_20170917_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='index_text',
            field=models.CharField(default='', max_length=100),
        ),
    ]
